package com.example.championsapplication.di

const val CHAMPIONS_LIST_VIEW_MODEL_TYPE = "CHAMPIONS_LIST_VIEW_MODEL_TYPE"
const val CHAMPIONS_DETAILS_VIEW_MODEL_TYPE = "CHAMPIONS_DETAILS_VIEW_MODEL_TYPE"